apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetmongocrudapp
  namespace: default
  labels:
    app: dotnetmongocrudapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetmongocrudapp
  template:
    metadata:
      labels:
        app: dotnetmongocrudapp
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5035"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: dotnet-sa
      containers:
        - name: dotnetmongocrudapp
          image: charansait372/dotnet-proj:v4
          ports:
            - containerPort: 5035
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:5035"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__CoreDB
              valueFrom:
                secretKeyRef:
                  name: sql-connection
                  key: connectionString
          readinessProbe:
            httpGet:
              path: /metrics
              port: 5035
            initialDelaySeconds: 10
            periodSeconds: 10

