apiVersion: v1
kind: Service
metadata:
  name: dotnetmongocrudapp-service
  namespace: default
  labels:
    app: dotnetmongocrudapp
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "80"
spec:
  selector:
    app: dotnetmongocrudapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
