apiVersion: v1
kind: Service
metadata:
  name: dotnetmongocrudapp-service
  namespace: default
  labels:
    app: dotnetmongocrudapp
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5035"
spec:
  selector:
    app: dotnetmongocrudapp
  ports:
  - protocol: TCP
    port: 80          # Cluster IP port (external service port)
    targetPort: 5035  # The REAL port inside your container
  type: ClusterIP
